name: "Rust simple release"
description: "Extremely simple all-in-one release for small rust project"

# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "slash"
  color: "green"

inputs:
  package:
    description: "package to build (you can only choose one)"
    required: false
    default: ""
  targets:
    description: "targets to build, split by comma(,)"
    required: false
    default: ""
  bin:
    description: "Binary output name. If you have multiple bins target, you must set this. Use package name by default."
    required: false
    default: ""
  features:
    description: "features to build, split by comma(,)"
    required: false
    default: ""
  files_to_pack:
    description: "relative file paths to compress to assets, split by comma(,)"
    required: false
    default: ""
  token:
    description: >
      GitHub token for creating GitHub Releases.

      If not set this option, the GITHUB_TOKEN environment variable will be used.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: dtolnay/rust-toolchain@stable
    - uses: cargo-bins/cargo-binstall@main
    - uses: goto-bus-stop/setup-zig@v2
    - shell: bash
      run: python "${GITHUB_ACTION_PATH:?}/main.py"
      env:
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_TARGETS: ${{ inputs.targets }}
        INPUT_BIN: ${{ inputs.bin }}
        INPUT_FEATURES: ${{ inputs.features }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILES_TO_PACK: ${{ inputs.files_to_pack }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
