[package]
name = "action-test"
repository = "https://github.com/lxl66566/rust-simple-release"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "my-action-test"
path = "src/main.rs"

[[bin]]
name = "my-action-test2"
path = "src/main2.rs"

[features]
test1 = []
